# name: Build

# on:
#     push:
#       branches:
#         - main
#         - release/*
#         - hotfix/*
#     pull_request:
#       types: [ready_for_review, opened, reopened, auto_merge_enabled]

# env:
#   GODOT_VERSION: 3.5.3
#   EXPORT_NAME: Savor22b
#   PROJECT_PATH: godot3

# jobs:
#     export-web:
#         name: Web Export
#         runs-on: ubuntu-20.04
#         container:
#           image: barichello/godot-ci:3.5.3
#         steps:
#           - name: Checkout
#             uses: actions/checkout@v2
#             with:
#               lfs: true
#           - name: Setup
#             run: |
#               mkdir -v -p ~/.local/share/godot/export_templates/
#               mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
#           - name: Web Build
#             run: |
#               mkdir -v -p build/web
#               cd $PROJECT_PATH
#               godot --headless --verbose --export-release "HTML5" ../build/web/index.html
#           - name: Upload Artifact
#             uses: actions/upload-artifact@v1
#             with:
#               name: web
#               path: build/web
